### ISSUE TITLE
Module 'App::Daemon' is not installed

### ISSUE THREAD

**Issue by luckypoem** [jmacdotorg/plerd#15]
hi.

root@AR:/usr/local# git clone https://github.com/jmacdotorg/plerd plerd-site
root@AR:/usr/local#  cd plerd-site
root@AR:/usr/local/plerd-site# curl -fsSL https://cpanmin.us | perl - --installdeps .
it shows:
...
Successfully installed Moose-2.2004
! Installing the dependencies failed: Module 'App::Daemon' is not installed
! Bailing out the installation for ..
89 distributions installed
root@AR:/usr/local/plerd-site#

how to fix it?

**Comment by jmacdotorg** [comment]
Is there any error or logging information behind that "..." which might have clues as to why App::Daemon did not install?

What happens if you try to install App::Daemon manually? (e.g. via "cpanm App::Daemon", or interactively via the "cpan" program)?

**Comment by jmacdotorg** [comment]
App::Daemon installs cleanly on a new latest-version Perl for me, and no further comment from the OP, so I'm closing this as unactionable.
