### ISSUE TITLE
Fatpack the webmention listener

### ISSUE THREAD

**Issue by iarna** [jmacdotorg/plerd#26]
One of the main selling points of Plerd to me was that it didn't require that I deploy any software to my server. (I was already syncing static files, all I had to do was set a docroot.)

Webmention support, of course, changes that. One way to reduce deployment friction would be to provide a fatbacked listener binary, that is, a single stand alone script that has all of its dependencies bundled into it.

https://metacpan.org/pod/distribution/App-FatPacker/bin/fatpack

I did this many years ago with this, though I'm sure there's a better way now:

https://github.com/iarna/App-Every/blob/master/build_fatpack.sh

**Comment by jmacdotorg** [comment]
To get a better idea of your specific use-case here:

You're interested in your blog receiving webmentions, but less thrilled about having to run an HTTP listener?

**Comment by iarna** [comment]
No, I'm fine with having a listener.

I'm less than thrilled about having to clone a project and install a bunch of Perl modules.

Having it as available as a cpan distribution would mitigate some of this, as it'd make the deploy on the server easier, but I'd prefer to not have to install anything globally on my servers. If it were available as a stand alone bin, I could just put that in my blog dir have it synced across with the rest of the site content. 

(If I were syncing a git clone, that wouldn't be available, because syncing wouldn't get dependencies, I'd still have to install the cpanfile any time it changed.)

The sum-up is that if at all possible, I don't install _anything_ globally on my servers if I can possibly avoid it. Node has kind of spoiled me in that respect, as there's no such thing as a global module.

**Comment by jmacdotorg** [comment]
> I'm less than thrilled about having to clone a project and install a bunch of Perl modules.

Other than its `cpanfile` being a little longer, I'm not sure how 1.6 (which introduced webmention support) differs from previous versions in this regard? (If you mean that you don't like that Plerd has ever required CPAN downloads at all, then that's a different matter... but you stated with this issue that something changed with 1.6, and I'm still uncertain about that.)

> The sum-up is that if at all possible, I don't install anything globally on my servers if I can possibly avoid it.

Not sure what you mean by "globally". Do you mean "available system-wide, for all users on the machine"?

**Comment by taskboy3000** [comment]
For the record, plenv has worked well for me and plerd. Less hassle than perlbrew.

—
Joe Johnston

**Comment by iarna** [comment]
> Other than its cpanfile being a little longer, I'm not sure how 1.6 (which introduced webmention support) differs from previous versions in this regard? 

I've never had any plerd on my servers at all.

I'm fine with plerd having dependencies on my laptop.

> Not sure what you mean by "globally". Do you mean "available system-wide, for all users on the machine"?

I mean "system-wide, for all _software_ on the machine". I only have one user. =p

Basically I'm trying to reduce the amount of sysadmin I have to do in order to support plerd. Having to install modules on the server or use plenv or perlbrew constitutes sysadmin that I'd rather not do.

**Comment by jmacdotorg** [comment]
> I've never had any plerd on my servers at all.

Oh!! I get it now. You're not the first person to tell me that they've used Plerd (modulo webmention) as an entirely local install, _but you may be the second_, so this use-case didn't occur to me without further explanation. (I have always run the scripts server-side!) 

I hear you now. That is a very interesting perspective, thank you.

On the CPAN front: Would it be good news to you if typing `cpanm Plerd` on the server as a non-root user did everything you needed to do, for both installing and upgrading Plerd and its dependencies, without having to mess around separately with perlbrew or plenv? (I *think* that would be a reasonable goal for me to achieve, without sounding terribly naive...)

**Comment by taskboy3000** [comment]
As mentioned, I run this on my server using plenv to isolate plerd in its own world. Arguably, docker might be a good fit for deloying plerd as well.

--Joe

**Comment by jmacdotorg** [comment]
@taskboy3000, Rebecca specifically said in her response that she would rather avoid setting up plenv (or building other system-administration environments) just for Plerd's sake, and I find that a fair desire.

It might be nice to start collecting different deployment styles on a wiki page or whatnot, if you wanted to note your own pattern someplace.

**Comment by jmacdotorg** [comment]
Closing this issue with https://github.com/jmacdotorg/plerd/commit/b63afc94ea221cf5f46066161a169cd152dda46a, which removes the webmention listener from Plerd.
